---
# ----------------------------------------------------------------------
# This is main playbook for vagrant init
# ----------------------------------------------------------------------

- name: Apply initial configuration for hosts dedicated to vagrant VM
  hosts: ossl-vagrant-init
  user: root
  sudo: no
  vars_prompt:
    - name: "vbox_version"
      prompt: "What is your VirtualBox version (example: 4.1.16)"
      default: "4.1.16"
      private: no
    - name: "selinux_status"
      prompt: "Should SELINUX be disabled: (yes/no)"
      default: "no"
      private: no

  roles:
    - ossl-vagrant-init

- name: Check access to vagrant VM as passwordless vagrant (sudo) user
  hosts: ossl-vagrant-init
  user: vagrant
  sudo: yes

  roles:
    - ossl-vagrant-ping
