---
# ----------------------------------------------------------------------
# Basic tasks to setup vagrant box
#
# Based on URL:
# http://docs-v1.vagrantup.com/v1/docs/base_boxes.html
# ----------------------------------------------------------------------

  # Disable SELinux
- name: Disable SELinux (file)
  lineinfile: dest=/etc/selinux/config regexp=^SELINUX= line=SELINUX=disabled

- name: Disable SELinux (command)
  command: /usr/sbin/setenforce Permissive
  ignore_errors: True

  # Common group and users
- name: Create required groups
  group: name={{ item.name }}  gid={{ item.gid }} state=present
  with_items:
    - { name: 'admin', gid: '509' }

- name: Create users with access to SSH
  user: name={{ item.name }} uid={{ item.uid }} comment={{ item.comment }} 
        state=present group=users groups={{ item.groups }}
  with_items:
    - { name: 'vagrant', comment: 'Vagrant\ default\ user', groups: 'admin', uid: '501' }

  # Sudo configuration
- name: Setup default password for vagrant user
  shell: echo "vagrant:vagrant" | chpasswd

- name: Install sudo (sometimes can be not installed)
  yum: name=sudo state=present

- name: Adjust sudo configuration
  copy: src={{ item.src }} dest={{ item.dest }} mode=0440 owner=root group=root
  with_items:
    - { src: 'sudo/sudoers', dest: '/etc/sudoers' }
    - { src: 'sudo/sudo_vagrant', dest: '/etc/sudoers.d/sudo_vagrant' }

  # SSH configuration
- name: Adjust main SSH configuration
  copy: src=ssh/sshd_config dest=/etc/ssh/sshd_config mode=0600 owner=root group=root
  notify:
    - restart sshd

- name: SSH configuration - Create /home/vagrant/.ssh folder
  file: dest=/home/vagrant/.ssh mode=0700 owner=vagrant group=users state=directory

  # https://github.com/mitchellh/vagrant/blob/master/keys/vagrant.pub
- name: SSH configuration - Install vagrant insecure SSH public key
  copy: src=vagrant/vagrant.pub dest=/home/vagrant/.ssh/authorized_keys 
        mode=0600 owner=vagrant group=users

  # Clean yum cache
- name: Clean yum cache
  shell: yum clean all
